### ISSUE TITLE
problem with customed blender synthetic dataset

### ISSUE THREAD

**Issue by dawning77** [liuyuan-pal/NeRO#25]
Thank you very much for your excellent work！
I use NeRO to process my own Blender synthetic dataset, in which objects bounding sphere radius is not 1.
I want to inquire you 3 questions:
1. how could I modify the code to change the setting of unit bounding sphere
(I have tried to change the inner mask, inner_sphere, near_far_from_sphere used in renderer.py)
2. how could the camera_world exported from Blender transform to your camera pose metric extracted from 'xxx_camera.pkl' 
(Is the [3,4] tensor being the opencv c2w rotating metric and the distance from origin to camera [0, 0, 3]? Is the rotating metric using opencv coordinate?)
Thanks again!!!

**Comment by liuyuan-pal** [comment]
Hi, thank you for your interest!
1. Instead of changing the unit sphere, I usually scale and offset the world coordinate system to make the object located inside the unit sphere. In case of the blender synthetic dataset, the object is already located at the origin so you may just scale it.
2. I use the opencv style w2c coordinate. You may refer to this https://github.com/liuyuan-pal/NeRO/issues/17#issuecomment-1654964004

**Comment by dawning77** [comment]
Thanks a lot! The scale_factor in database.py really helps!
