### ISSUE TITLE
how to improve the quality of BRDF estimation stage.

### ISSUE THREAD

**Issue by blacksino** [liuyuan-pal/NeRO#31]
Hello, I have been training second stage BRDF estimation network with an existing mesh and multiview images for days, exploring your great job.
The result seems to a bit oversmoothed and blurry, how could I improve BRDF estimation quality?

<img width="800" alt="截屏2023-11-06 11 44 27" src="https://github.com/liuyuan-pal/NeRO/assets/44363764/8ad58643-c44a-416c-9b88-9ee47375c2c7">

**Comment by liuyuan-pal** [comment]
Hi, I'm not sure about the simple tricks to improve it because inverse rendering is an ill-posed problem. It would be easier to have a reflective object which contains more information about the environment lights.
1) It is indeed difficult for MLP networks to encode the high-frequency texture on the model. Changing it to hash-grid-like representation will enable the albedo to produce more details.
2) Maybe, you can reduce the smoothness loss weights to prevent oversmooth.

**Comment by blacksino** [comment]
感谢您的回复！
1.您的意思是如果MLP无法编码高频纹理的话，将您repo中二阶段的纹理网络从普通的MLP换成TCNN中的hashgrid encode方式也许会有帮助吗。
2.经过实验，帮助不大。

**Comment by blacksino** [comment]
而且请问为啥材质的metallic这么大，导致漫反射颜色基本为0呢

**Comment by liuyuan-pal** [comment]
你好，这里其实是存在一个ambiguity的问题的。像这种反射不是特别强的物体上的材质，它很难判断到底是1）物体强反射，环境光变化 还是2）物体弱反射，物体上有很多纹理变化的。然后这里光照的MLP比较大，它用光照去拟合颜色更容易，那么就会收敛到金属的反射材质上。

如果场景内存在一个强反射的物体，那么它就能提供光照的信息，就能帮助判断其他部分的材质。而场景内只有弱反射的物体就很难获取到光照的信息。

**Comment by blacksino** [comment]
非常感谢您耐心的回答，逆渲染确实是一个难度很大的病态问题。
